const fs = require("fs");
const { ethers } = require("ethers");

const INPUT = "scripts/gmx/gmx_fallback_feeds_with_multipliers.json";
const CONTRACT = "contracts/protocol/types/GmxFallback.sol";
const TEST_CONTRACT = "test/libraries/GmxFallback.t.sol";
const FORK_TEST_CONTRACT = "test/extensions/AGmxV2Fork.t.sol";
const FORK_START_MARKER = "// GMX_FALLBACK_FORK_TESTS_START";
const FORK_END_MARKER = "// GMX_FALLBACK_FORK_TESTS_END";

const fallback = JSON.parse(fs.readFileSync(INPUT, "utf8"));

// Sort by checksummed token address using numeric order, required by the batched lookup.
const sorted = fallback
  .map((e) => ({ ...e, token: ethers.utils.getAddress(e.indexToken) }))
  .sort((a, b) => {
    const aBig = BigInt.asUintN(160, BigInt(a.token));
    const bBig = BigInt.asUintN(160, BigInt(b.token));
    return aBig < bBig ? -1 : aBig > bBig ? 1 : 0;
  });

function computeExponent(multiplier) {
  const str = multiplier.toString();
  if (!/^10*$/.test(str)) {
    throw new Error(`Multiplier ${multiplier} is not a power of 10`);
  }
  return str.length - 1;
}

function packEntry(e) {
  const exponent = computeExponent(e.multiplier);
  const feed = BigInt.asUintN(160, BigInt(e.feedAddress));
  // Pack feed address (160 bits) in the high 160 bits and the exponent in the low 8 bits.
  // Using uint168 instead of bytes32 saves ~11 bytes of deployed bytecode per entry.
  const packed = (feed << 8n) | BigInt.asUintN(8, BigInt(exponent));
  return `0x${packed.toString(16).padStart(42, "0")}`;
}

function firstNibble(token) {
  return (BigInt.asUintN(160, BigInt(token)) >> 156n).toString(10);
}

function buildGroups() {
  // Groups by leading hex nibble of the token address. Each branch is a small
  // integer comparison, which is cheaper and more compact than comparing a
  // full 20-byte boundary address.
  const boundaries = [3, 7, 10, 13];
  const groups = boundaries.map((bound) => ({ bound, entries: [] }));
  const lastGroup = { entries: [] };

  for (const e of sorted) {
    const nibble = firstNibble(e.token);
    let placed = false;
    for (const g of groups) {
      if (nibble < g.bound) {
        g.entries.push(e);
        placed = true;
        break;
      }
    }
    if (!placed) lastGroup.entries.push(e);
  }

  return { bounded: groups, last: lastGroup };
}

function emitEntry(e) {
  const packed = packEntry(e);
  return `        if (token == ${e.token}) packed = ${packed};`;
}

function buildLookupBlock() {
  const { bounded, last } = buildGroups();
  const lines = [];

  for (let i = 0; i < bounded.length; ++i) {
    const g = bounded[i];
    const keyword = i === 0 ? "if" : "} else if";
    lines.push(`    ${keyword} (nibble < ${g.bound}) {`);
    for (const e of g.entries) {
      lines.push(emitEntry(e));
    }
  }

  if (last.entries.length > 0) {
    lines.push("    } else {");
    for (const e of last.entries) {
      lines.push(emitEntry(e));
    }
  }
  lines.push("    }");

  return lines.join("\n");
}

function patchContract() {
  const sol = fs.readFileSync(CONTRACT, "utf8");
  const startMarker = "    // GMX_FALLBACK_LOOKUP_START";
  const endMarker = "    // GMX_FALLBACK_LOOKUP_END";

  const startIdx = sol.indexOf(startMarker);
  const endIdx = sol.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    throw new Error(
      `Could not find fallback markers in ${CONTRACT}. ` +
        `Expected '${startMarker}' and '${endMarker}'.`,
    );
  }

  const before = sol.slice(0, startIdx);
  const after = sol.slice(endIdx + endMarker.length);
  const replacement = `${startMarker}\n${buildLookupBlock()}\n${endMarker}`;

  fs.writeFileSync(CONTRACT, before + replacement + after, "utf8");
  console.log(
    `Patched ${CONTRACT} with ${sorted.length} packed fallback entries (${new Date().toISOString()})`,
  );
}

function buildTestFile() {
  const lines = [
    "// SPDX-License-Identifier: Apache-2.0-or-later",
    "pragma solidity ^0.8.28;",
    "",
    'import {Test} from "forge-std/Test.sol";',
    'import {GmxFallback, Feed, getFallbackPriceFeed} from "../../contracts/protocol/types/GmxFallback.sol";',
    "",
    "/// @title GmxFallbackTest",
    "/// @notice Regression tests for the hardcoded GMX fallback feed registry.",
    "/// @dev This file is generated by scripts/gmx/generate_gmx_fallback_solidity.js.",
    "///  Do not edit manually; re-run the generator after updating the JSON source.",
    "contract GmxFallbackTest is Test {",
    "    struct FallbackEntry {",
    "        address token;",
    "        address feed;",
    "        uint8 feedDecimals;",
    "        uint8 tokenDecimals;",
    "        uint8 exponent;",
    "    }",
    "",
    "    FallbackEntry[] internal entries;",
    "",
    "    constructor() {",
  ];

  for (const e of sorted) {
    const exponent = computeExponent(e.multiplier);
    lines.push(
      `        entries.push(FallbackEntry(${e.token}, ${e.feedAddress}, ${e.feedDecimals}, ${e.tokenDecimals}, ${exponent}));`,
    );
  }

  lines.push(
    "    }",
    "",
    "    /// @notice Every hardcoded fallback entry must return the correct feed address and exponent.",
    "    /// @dev The expected exponent is derived from the fixed formula used by the generator:",
    "    ///  `exponent = 60 - feedDecimals - tokenDecimals`. This catches accidental script edits",
    "    ///  that produce a multiplier inconsistent with the feed and token decimal scales.",
    "    function test_AllMappedFallbackFeeds_AreValid() public view {",
    "        for (uint256 i; i < entries.length; ++i) {",
    "            FallbackEntry memory e = entries[i];",
    "            Feed packed = getFallbackPriceFeed(e.token);",
    "            uint256 data = Feed.unwrap(packed);",
    "",
    "            address feed = address(uint160(data >> 8));",
    "            uint8 exponent = uint8(data & type(uint8).max);",
    "            uint8 expectedExponent = 60 - e.feedDecimals - e.tokenDecimals;",
    "",
    '            assertEq(feed, e.feed, "fallback feed address mismatch");',
    '            assertEq(exponent, e.exponent, "fallback exponent mismatch");',
    '            assertEq(exponent, expectedExponent, "fallback exponent does not match 60 - feedDecimals - tokenDecimals");',
    "        }",
    "    }",
    "",
    "    /// @notice Any token not in the hardcoded mapping must return the zero feed address.",
    "    function test_UnmappedToken_ReturnsZeroFeed() public view {",
    "        Feed packed = getFallbackPriceFeed(address(0xdead));",
    "        uint256 data = Feed.unwrap(packed);",
    "        assertEq(address(uint160(data >> 8)), address(0));",
    "    }",
    "}",
  );

  return lines.join("\n");
}

function buildForkTestSection() {
  const lines = [
    "    /// @dev Fork tests that verify the hardcoded fallback metadata matches on-chain reality.",
    "    ///  This section is generated by scripts/gmx/generate_gmx_fallback_solidity.js.",
    "    ///  Do not edit manually; re-run the generator after updating the JSON source.",
    "    /// @dev Forks at the pinned `Constants.ARB_BLOCK` (see ForkBlocks.sol): CI caches fork state per",
    "    ///  block, so the baseline is fixed and not re-fetched on every run. Loud failures with a",
    '    ///  "bump ForkBlocks.ARB_BLOCK" hint mean the token was listed after the pinned block — update',
    "    ///  the block deliberately. The freshness assertion instead means the feed was already stale at",
    "    ///  the pinned block, i.e. the mapping entry is dead and should be removed.",
    "    struct FallbackEntry {",
    "        address token;",
    "        address feed;",
    "        uint8 feedDecimals;",
    "        uint8 tokenDecimals;",
    "        uint8 exponent;",
    "    }",
    "",
    "    FallbackEntry[] internal fallbackEntries;",
    "",
    "    constructor() {",
  ];

  for (const e of sorted) {
    const exponent = computeExponent(e.multiplier);
    lines.push(
      `        fallbackEntries.push(FallbackEntry(${e.token}, ${e.feedAddress}, ${e.feedDecimals}, ${e.tokenDecimals}, ${exponent}));`,
    );
  }

  lines.push(
    "    }",
    "",
    "    /// @dev GMX stores `tokenDecimals` for synthetic index tokens only as the on-chain",
    "    ///  Data Stream multiplier `10^(42 - tokenDecimals)`. Deriving it from there — rather",
    "    ///  than trusting any local config — is what catches a wrong table row.",
    "    function _gmxTokenDecimals(address token) internal view returns (uint256) {",
    '        bytes32 prefix = keccak256(abi.encode("DATA_STREAM_MULTIPLIER"));',
    "        bytes32 key = keccak256(abi.encode(prefix, token));",
    "        uint256 multiplier = IGmxDataStore(_GMX_DATA_STORE).getUint(key);",
    "        require(",
    "            multiplier != 0,",
    '            "missing GMX DATA_STREAM_MULTIPLIER at pinned ARB_BLOCK - token listed later? bump ForkBlocks.ARB_BLOCK"',
    "        );",
    "",
    "        uint256 exponent;",
    "        uint256 m = multiplier;",
    "        while (m >= 10) {",
    "            m /= 10;",
    "            unchecked {",
    "                ++exponent;",
    "            }",
    "        }",
    '        require(m == 1, "GMX DATA_STREAM_MULTIPLIER is not a power of 10");',
    "        return 42 - exponent;",
    "    }",
    "",
    "    /// @notice The hardcoded Chainlink feed decimals match the on-chain aggregator and the",
    "    ///  packed exponent matches GMX's own on-chain token decimals, so the multiplier can",
    "    ///  never again silently assume the wrong token scale (e.g. a default of 18).",
    "    function test_FallbackMetadata_MatchesOnChainGmxConfig() public {",
    '        vm.createSelectFork("arbitrum", Constants.ARB_BLOCK);',
    "",
    "        for (uint256 i; i < fallbackEntries.length; ++i) {",
    "            FallbackEntry memory e = fallbackEntries[i];",
    "",
    "            require(",
    "                e.feed.code.length != 0,",
    '                "feed has no code at pinned ARB_BLOCK - token listed later? bump ForkBlocks.ARB_BLOCK"',
    "            );",
    "",
    "            uint8 onChainFeedDecimals = IPriceFeed(e.feed).decimals();",
    '            assertEq(onChainFeedDecimals, e.feedDecimals, "on-chain feed decimals mismatch");',
    "",
    "            uint256 gmxTokenDecimals = _gmxTokenDecimals(e.token);",
    '            assertEq(gmxTokenDecimals, e.tokenDecimals, "GMX token decimals mismatch");',
    "",
    "            Feed packed = getFallbackPriceFeed(e.token);",
    "            uint256 data = Feed.unwrap(packed);",
    "            uint8 exponent = uint8(data & type(uint8).max);",
    "            uint8 expectedExponent = 60 - e.feedDecimals - uint8(gmxTokenDecimals);",
    '            assertEq(exponent, expectedExponent, "packed exponent inconsistent with on-chain GMX config");',
    "        }",
    "    }",
    "",
    "    /// @notice End-to-end: the price returned by `getFallbackPrice` equals the live Chainlink",
    "    ///  answer scaled by `10^(60 - feedDecimals - gmxTokenDecimals) / 1e30`, where",
    "    ///  `gmxTokenDecimals` comes from GMX's on-chain DATA_STREAM_MULTIPLIER. This asserts the",
    "    ///  packed multiplier produces the correct absolute price, not just a self-consistent one.",
    "    function test_GetFallbackPrice_MatchesLiveFeedScaling() public {",
    '        vm.createSelectFork("arbitrum", Constants.ARB_BLOCK);',
    "",
    "        uint256[] memory expectedPrices = new uint256[](fallbackEntries.length);",
    "        uint256 maxUpdatedAt;",
    "",
    "        for (uint256 i; i < fallbackEntries.length; ++i) {",
    "            FallbackEntry memory e = fallbackEntries[i];",
    "            require(",
    "                e.feed.code.length != 0,",
    '                "feed has no code at pinned ARB_BLOCK - token listed later? bump ForkBlocks.ARB_BLOCK"',
    "            );",
    "            (, int256 answer, , uint256 updatedAt, ) = IPriceFeed(e.feed).latestRoundData();",
    "            require(",
    "                answer > 0,",
    '                "non-positive feed answer at pinned ARB_BLOCK - feed deployed later? bump ForkBlocks.ARB_BLOCK"',
    "            );",
    "",
    "            // A mapped feed must be live: in production a feed stale by more than the 24h",
    "            // heartbeat (_FALLBACK_HEARTBEAT) yields a zero price, i.e. a dead mapping entry.",
    "            // Assert freshness at fork time, before the warp below masks it.",
    '            assertGe(updatedAt + 24 hours, block.timestamp, "mapped feed is stale past the 24h heartbeat");',
    "",
    "            uint256 gmxTokenDecimals = _gmxTokenDecimals(e.token);",
    "            expectedPrices[i] =",
    "                (uint256(answer) * 10 ** (60 - e.feedDecimals - uint8(gmxTokenDecimals))) / _FLOAT_PRECISION;",
    "",
    "            if (updatedAt > maxUpdatedAt) maxUpdatedAt = updatedAt;",
    "        }",
    "",
    "        // Make the 24h heartbeat check deterministic regardless of the fork block timestamp.",
    "        vm.warp(maxUpdatedAt + 1);",
    "",
    "        for (uint256 i; i < fallbackEntries.length; ++i) {",
    "            Price.Props memory price = GmxFallback.getFallbackPrice(fallbackEntries[i].token);",
    '            assertGt(price.min, 0, "fallback price is zero");',
    '            assertEq(price.min, price.max, "fallback price min != max");',
    '            assertEq(price.min, expectedPrices[i], "fallback price != live answer with expected scaling");',
    "        }",
    "    }",
  );

  return lines.join("\n");
}

function patchTest() {
  fs.writeFileSync(TEST_CONTRACT, buildTestFile(), "utf8");
  console.log(
    `Patched ${TEST_CONTRACT} with ${sorted.length} fallback assertions (${new Date().toISOString()})`,
  );
}

function patchForkTest() {
  const sol = fs.readFileSync(FORK_TEST_CONTRACT, "utf8");
  const startIdx = sol.indexOf(FORK_START_MARKER);
  const endIdx = sol.indexOf(FORK_END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    throw new Error(
      `Could not find fallback fork test markers in ${FORK_TEST_CONTRACT}. ` +
        `Expected '${FORK_START_MARKER}' and '${FORK_END_MARKER}'.`,
    );
  }

  const before = sol.slice(0, startIdx + FORK_START_MARKER.length);
  const after = sol.slice(endIdx);
  const replacement = `${before}\n${buildForkTestSection()}\n${after}`;

  fs.writeFileSync(FORK_TEST_CONTRACT, replacement, "utf8");
  console.log(
    `Patched ${FORK_TEST_CONTRACT} with ${sorted.length} on-chain decimal checks (${new Date().toISOString()})`,
  );
}

function printToStdout() {
  console.log(
    "// Sorted fallback price feeds for GMX index tokens without a GMX priceFeed",
  );
  console.log("// Source: Chainlink on-chain aggregators on Arbitrum");
  console.log("// Generated on", new Date().toISOString());
  console.log("");
  console.log(buildLookupBlock());
}

if (process.argv.includes("--stdout")) {
  printToStdout();
} else {
  patchContract();
  patchTest();
  patchForkTest();
}
