// SPDX-License-Identifier: Apache-2.0-or-later
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {GmxFallback, Feed, getFallbackPriceFeed} from "../../contracts/protocol/types/GmxFallback.sol";

/// @title GmxFallbackTest
/// @notice Regression tests for the hardcoded GMX fallback feed registry.
/// @dev This file is generated by scripts/gmx/generate_gmx_fallback_solidity.js.
///  Do not edit manually; re-run the generator after updating the JSON source.
contract GmxFallbackTest is Test {
    struct FallbackEntry {
        address token;
        address feed;
        uint8 feedDecimals;
        uint8 tokenDecimals;
        uint8 exponent;
    }

    FallbackEntry[] internal entries;

    constructor() {
        entries.push(
            FallbackEntry(
                0x0315441076FF6d3eA09814a2F90a1f980cF03e9e,
                0x46306F3795342117721D8DEd50fbcF6DF2b3cc10,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x13674172E6E44D31d4bE489d5184f3457c40153A,
                0x8c76E8cab5ef3B410a318DDb82d83Ed47D7d2701,
                8,
                12,
                40
            )
        );
        entries.push(
            FallbackEntry(
                0x13983f27Ce9365055a6a553233c49fE28e70103e,
                0xCCa91A477fBF466D676B2056bfDfDA94f343a64F,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x197aa2DE1313c7AD50184234490E12409B2a1f95,
                0x4a85B128EBDaFC24d5CB611e161376ffDECeB289,
                8,
                9,
                43
            )
        );
        entries.push(
            FallbackEntry(
                0x2aAB60E62f05d17e58dEc982870bfAdc7F4e7ADF,
                0xAD57D7c059E2aFef2241EB6EF43559f8a409897E,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x2e73bDBee83D91623736D514b0BB41f2afd9C7Fd,
                0x1b47b4124b9A5094C59710E6b9126e5e32a4fb8E,
                18,
                18,
                24
            )
        );
        entries.push(
            FallbackEntry(
                0x3E57D02f9d196873e55727382974b02EdebE6bfd,
                0x0E278D14B4bf6429dDB0a1B353e2Ae8A4e128C93,
                18,
                18,
                24
            )
        );
        entries.push(
            FallbackEntry(
                0x3f8f0dCE4dCE4d0D1d0871941e79CDA82cA50d0B,
                0xdc49F292ad1bb3DAb6C11363d74ED06F38b9bd9C,
                8,
                8,
                44
            )
        );
        entries.push(
            FallbackEntry(
                0x4b9a2b862E1a30e6E844c991D31Dc6387c9d65D5,
                0x26DC0763135Db2EC0dC4563148AC57eB48Ed0BAd,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x55e85A147a1029b985384822c0B2262dF8023452,
                0xCc9742d77622eE9abBF1Df03530594f9097bDcB3,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x67ADABbAd211eA9b3B4E2fd0FD165E593De1e983,
                0x4f861F14246229530a881D32C8d26D78b8c48BE6,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x6eAbbaA3278556Dc5b19c034dc26c0eaB60d65B5,
                0x21082CA28570f0ccfb089465bFaEfDc77b00D367,
                18,
                18,
                24
            )
        );
        entries.push(
            FallbackEntry(
                0x8F6cCb99d4Fd0B4095915147b5ae3bbDb8075394,
                0xFeaC1A3936514746e70170c0f539e70b23d36F19,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x95c317066CF214b2E6588B2685D949384504F51e,
                0x47C38C695639aE97A00f57D6D9f5ece1DebB033C,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x9759C297fb6C91e252c7292cECa30a509558E5De,
                0xA0C8611b0CfB31Bc8AdE3189ae2b982c90D9302f,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x97Ce1F309B949f7FBC4f58c5cb6aa417A5ff8964,
                0x17d8D87dF3E279c737568aB0C5cC3fF750aB763e,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0x9c060B2fA953b5f69879a8B7B81f62BFfEF360be,
                0x0C997958ccE7A0403AEA7E34d14bbaDA897B5bb3,
                18,
                18,
                24
            )
        );
        entries.push(
            FallbackEntry(
                0x9c74772b713a1B032aEB173E28683D937E51921c,
                0x82BA56a2fADF9C14f17D08bc51bDA0bDB83A8934,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0xB2f7cefaeEb08Aa347705ac829a7b8bE2FB560f3,
                0x0301e5D0A8f7490444ebd1921E3d0f0fe7722786,
                8,
                9,
                43
            )
        );
        entries.push(
            FallbackEntry(
                0xB46A094Bc4B0adBD801E14b9DB95e05E28962764,
                0x5698690a7B7B84F6aa985ef7690A8A7288FBc9c8,
                8,
                8,
                44
            )
        );
        entries.push(
            FallbackEntry(
                0xB79Eb5BA64A167676694bB41bc1640F95d309a2F,
                0xE56BEA9Ff0780D668f92a9ab4Ace1D713CaA1016,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0xBaf07cF91D413C0aCB2b7444B9Bf13b4e03c9D71,
                0x3a9659C071dD3C37a8b1A2363409A8D41B2Feae3,
                8,
                6,
                46
            )
        );
        entries.push(
            FallbackEntry(
                0xC5799ab6E2818fD8d0788dB8D156B0c5db1Bf97b,
                0x4b13Dd76De990Db9A2Dab58D35C2c02E5e3AE848,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0xc5dbD52Ae5a927Cf585B884011d0C7631C9974c6,
                0x5a0a07CD0E9e4754B3FeC4Fb1ee1a5baBbaa6051,
                18,
                7,
                35
            )
        );
        entries.push(
            FallbackEntry(
                0xE6172EecBB07F197F52bb73d74daa0e19C31c4Db,
                0x569dCA98c58d7A89cEE87801805A8EaAf2C72B5b,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0xEcc5eb985Ddbb8335b175b0A2A1144E4c978F1f6,
                0x0B2aB7AE5276F6f466f8e62953138B106dD19A63,
                8,
                18,
                34
            )
        );
        entries.push(
            FallbackEntry(
                0xF67b2a901D674B443Fa9f6DB2A689B37c07fD4fE,
                0x1E48733Eeee02468b674b69958b046EB6A0a7d94,
                8,
                18,
                34
            )
        );
    }

    /// @notice Every hardcoded fallback entry must return the correct feed address and exponent.
    /// @dev The expected exponent is derived from the fixed formula used by the generator:
    ///  `exponent = 60 - feedDecimals - tokenDecimals`. This catches accidental script edits
    ///  that produce a multiplier inconsistent with the feed and token decimal scales.
    function test_AllMappedFallbackFeeds_AreValid() public view {
        for (uint256 i; i < entries.length; ++i) {
            FallbackEntry memory e = entries[i];
            Feed packed = getFallbackPriceFeed(e.token);
            uint256 data = Feed.unwrap(packed);

            address feed = address(uint160(data >> 8));
            uint8 exponent = uint8(data & type(uint8).max);
            uint8 expectedExponent = 60 - e.feedDecimals - e.tokenDecimals;

            assertEq(feed, e.feed, "fallback feed address mismatch");
            assertEq(exponent, e.exponent, "fallback exponent mismatch");
            assertEq(exponent, expectedExponent, "fallback exponent does not match 60 - feedDecimals - tokenDecimals");
        }
    }

    /// @notice Any token not in the hardcoded mapping must return the zero feed address.
    function test_UnmappedToken_ReturnsZeroFeed() public view {
        Feed packed = getFallbackPriceFeed(address(0xdead));
        uint256 data = Feed.unwrap(packed);
        assertEq(address(uint160(data >> 8)), address(0));
    }
}
